### ISSUE TITLE
Images not being pushed into Dynamics Accounts

### ISSUE THREAD

**Issue by Lorry77** [rajyraman/Ryr.XrmToolBox.EntityImageUpdater#10]
[Write your comment/feedback/issue here]
Hi, this tool is exactly what I need, however, it doesn't seem to be pushing the images that it finds for the account (renamed to customer) into Dynamics. 

As you can see from the screenshot below it is finding the images from the websites but when I open them in Dynamics the image hasn't been uploaded. Not sure if I am doing something wrong or if this is a bug. 
Thanks. Dan

![image](https://user-images.githubusercontent.com/63688131/79289329-0e5d5c00-7f1d-11ea-8c5a-8a1ec99351d6.png)

![image](https://user-images.githubusercontent.com/63688131/79289501-8297ff80-7f1d-11ea-91a7-8ebec43063a0.png)

---
- Deployment: Online
- DB Version: 9.1.0.15941
- XTB Version: 1.2020.2.37
- Tool Version: 2.2.0.0

**Comment by rajyraman** [comment]
@Lorry77 - I tried this today and the image was updated. Can you check the Website field on all the records and see whether they contain some weird data, or trace to Fiddler? Selective update does not work currently as I have not updated the FetchXML Builder assembly reference. I will try to update the tool to reference the latest FXB over the weekend.

**Comment by Lorry77** [comment]
Hi Natraj

Thanks for your email. I have checked the website field and there is no weird data.

I then tested using a different URL field called Facebook and ran Update All. Once again it returns the images OK, but does not upload them to Dynamics.

[cid:f5d849e9-f587-430d-99de-73568c85102a]
[cid:f8876d9b-4e14-48f0-ad80-3e295a0d9304]
 Thanks
Dan



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Lorry77** [comment]
Hi, I have tested for contacts and it works fine however, it is not working for account for some reason.

Do you have any ideas on why this would be the case

Thanks
Dan


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by rajyraman** [comment]
@Lorry77 - Are there any plugins on Account? Maybe some plugin/realtime workflow is blocking the update? Can you run Fiddler and see what is happening?

**Comment by Lorry77** [comment]
Turns out there was another image field on the form that set as the primary image for account. Which for some reason couldn’t be changed back to the default image field. So I had to delete the extra image field which wasn’t being used anyway and it works now. Cheers.

Sent from my iPhone

On 22/04/2020, at 4:28 PM, Natraj Yegnaraman <notifications@github.com<mailto:notifications@github.com>> wrote:


@Lorry77<https://github.com/Lorry77> - Are there any plugins on Account? Maybe some plugin/realtime workflow is blocking the update? Can you run Fiddler and see what is happening?
